settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.jam0x3a.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  #- id: riders-ran
    #name: RidersRAN
    #url: 'https://riders-ran.xyz/'
    #method: GET
    #expectStatus: 503 #200

  - id: qpax-tcms # unique identifier
    name: QPax Beanstalk AWS
    description: 'QPax Beanstalk AWS' # default=empty
    url: 'http://tcmsmobilebackendstaging-env.eba-3ippmw5s.ap-southeast-1.elasticbeanstalk.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: Cloudflare
    #description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: jamilbulanadi-com
    name: TCMS Backend - Staging
    url: 'https://mobile-backend.qpax-tcms.net/'
    method: GET
    expectStatus: 200
    linkable: false #--
 
  - id: tri-m
    name: RidersRAN
    url: 'https://riders-ran.xyz/'
    method: GET
    expectStatus: 200
    linkable: false #--
    followRedirect: false #--
    
  - id: github-com
    name: Github
    url: 'https://github.com/'
    method: GET
    expectStatus: 200
